CREATE TABLE ARTIST {
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(1000)
};

CREATE TABLE ALBUM {
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    ARTIST_ID INT NOT NULL,
    FOREIGN KEY (ARTIST_ID) REFERENCES ARTIST(ID)
};

CREATE TABLE SONG {
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    ALBUM_ID INT NOT NULL,
    FOREIGN KEY (ALBUM_ID) REFERENCES ALBUM(ID)
};

CREATE TABLE PLAYLIST {
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(1000)
};

CREATE TABLE PLAYLIST_SONG {
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PLAYLIST_ID INT NOT NULL,
    SONG_ID INT NOT NULL,
    FOREIGN KEY (PLAYLIST_ID) REFERENCES PLAYLIST(ID),
    FOREIGN KEY (SONG_ID) REFERENCES SONG(ID)
};

