SELECT RELEASED_ON.POSITION, SONG.NAME, SONG.DURATION, SONG.GENRE
FROM RELEASED_ON INNER JOIN SONG ON RELEASED_ON.SONG_ID = SONG.ID INNER JOIN ARTIST ON SONG.ARTIST_ID = ARTIST.ID
WHERE RELEASED_ON.ALBUM_ID = get_album_id('Evermore')
ORDER BY RELEASED_ON.POSITION ASC;
